[versions]
agp = "8.7.3"
kotlin = "2.1.0"
composeMultiplatform = "1.7.3"
androidxActivityCompose = "1.9.3"
androidxCredentials = "1.3.0"
googleId = "1.1.1"
androidCompileSdk = "36"
androidMinSdk = "26"
androidTargetSdk = "36"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidxCredentials" }
androidx-credentials-play-services = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidxCredentials" }
google-id = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleId" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
